Repository finos/common-domain-model, pull requests merged in 2023-03, with the labels that each got.

#1999 ben.aubry_auth0_60be7cbc9d409a0069cd0f72-bondReference_couponRate
  RELEASE.md
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
Labels: ready for release

#2071 Update DSL version to 7.3.1 and bundle version 5.9.0
  RELEASE.md
  cdm-distribution/csharp8-pom.xml
  cdm-distribution/csharp9-pom.xml
  cdm-distribution/daml-pom.xml
  cdm-distribution/golang-pom.xml
  cdm-distribution/kotlin-pom.xml
  cdm-distribution/pom.xml
  cdm-distribution/scala-pom.xml
  cdm-distribution/typescript-pom.xml
  isda-demo/pom.xml
  pom.xml
  rosetta-project/pom.xml
  rosetta-source/pom.xml
  scheme-import/pom.xml
  tests/pom.xml
Labels: Minor Enhancement/Change

#2067 (3.x.x) Commodity product mappings
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-synonym.rosetta
Labels: ready for release, Minor Enhancement/Change

#2060 Task 5015: Addition of Clearing Receipt Date Time in EventTimestampQualificationEnum in CDM
  RELEASE.md
  rosetta-source/src/main/rosetta/event-workflow-enum.rosetta
Labels: Minor Enhancement/Change

#2078 (3.x.x) Update bundle version to 5.9.1 (ingestion test json assert fix)
  pom.xml
Labels: Patch/Documentation

#2077 Update bundle version to 5.9.1 (ingestion test json assert fix)
  pom.xml
Labels: Patch/Documentation
