Repository finos/common-domain-model, pull requests merged in 2023-07, with the labels that each got.

#2237 CVE vulnerability CVE-2023-35116 (suppressed) and CVE-2023-2976 (fixed in bundle version 6.7.4)
  .github/workflows/cve-scanning.yml
  .github/workflows/license-scanning.yml
  allow-list.xml
  pom.xml
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/Basis-ex01-LIBOR-vs-SOFR-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/FRA-ex01-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/FRA-ex02-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex01-Fixed-Float-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex02-Fixed-Float-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex03-Fixed-Float-with-Amortizing-Schedule-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex04-Fixed-Float-with-Compounding-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex05-Fixed-Float-with-Long-Stub-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex06-Fixed-Float-Non-Deliverable-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex07-Fixed-Float-Zero-Coupon-BRL-CDI-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex08-Fixed-Float-Zero-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex09-OIS-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex10-OIS-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/IRS-ex11-OIS-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/SWAPTION_TERMINATED_DUE_TO_EXERCISE-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/SWAP_CREATED_DUE_TO_EXERCISE-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/Swaption-ex01-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/Swaption-ex02-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/cme-cleared-confirm-1-17/Swaption-ex03-Straddle-Physical-Exercise-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade1-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade2-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade3-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade4-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade5-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade6-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-cleared-alpha-trade-CFTC-SEC-and-canada-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex51-execution-advice-trade-initiation-C01-00-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex52-execution-advice-trade-partial-novation-C02-00-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex53-execution-advice-trade-partial-novation-correction-C02-10-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex58-execution-advice-trade-initiation-F01-00-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex63-execution-advice-trade-initiation-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-new-alpha-trade-CFTC-SEC-and-canada-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-new-beta-trade-CFTC-SEC-and-canada-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-new-trade-CFTC-SEC-and-canada-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-new-trade-CFTC-clearing-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-partial-termination-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-partial-termination-xccy-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-partial-termination-xccy-swap-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/workflow-step/cancellation/cancellation-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/workflow-step/correction/correction-func-output.json
Labels: Category:Technical, Criticality:High, Complexity:Small, Target:Development

#2236 Added Python unit tests to confirm that generated code performs as expected
  .gitignore
  codefresh.yml
  rosetta-source/pom.xml
  rosetta-source/src/main/resources/build-resources/create-deploy-pom.py
  rosetta-source/src/main/resources/build-resources/python/python-developer.txt
  rosetta-source/src/test/python/run_tests.sh
  rosetta-source/src/test/python/semantics/test_cardinality.py
  rosetta-source/src/test/python/semantics/test_conditions.py
  rosetta-source/src/test/python/semantics/test_if_cond.py
  rosetta-source/src/test/python/serialization/cdm_comparison_test.py
  rosetta-source/src/test/python/serialization/dict_comp.py
  rosetta-source/src/test/python/serialization/test_trade_state_product.py
Labels: Category:Technical, Target:Development, Criticality:Medium, Complexity:Medium

#2221 Adjusted 'specification' instead of 'schedule'
  documentation/source/eligible-collateral-representation.rst
  documentation/source/images/cdm-graphical-ecs.png
Labels: Complexity:Small, Category:Documentation, Criticality:Medium, Target:Production

#2240 ForwardPayout should extend PayoutBase
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/incomplete-products/fx-derivatives/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/processes/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/products/fx/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-12/products/fx/expectations.json
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-incomplete-products-credit-derivatives-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-invalid-products-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-products-dividend-swaps-failed-mappings-report.csv
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/fx-derivatives/fx-ex26-fxswap-multiple-USIs.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/fx-derivatives/fx-ex29-fx-swap-with-multiple-identifiers.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/processes/msg-partial-termination-xccy.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex01-fx-spot.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex02-spot-cross-w-side-rates.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex03-fx-fwd.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex04-fx-fwd-w-settlement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex05-fx-fwd-w-ssi.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex06-fx-fwd-w-splits.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex07-non-deliverable-forward.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex08-fx-swap.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex28-non-deliverable-w-disruption.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex01-fx-spot.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex02-spot-cross-w-side-rates.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex03-fx-fwd.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex04-fx-fwd-w-settlement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex05-fx-fwd-w-ssi.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex06-fx-fwd-w-splits.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex07-non-deliverable-forward.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex08-fx-swap.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex28-non-deliverable-w-disruption.json
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity:Small, Target:Development, Criticality:Medium, Category:Modelling

#2244 DSL 8.2.0: conversion operations
  RELEASE.md
  examples/pom.xml
  examples/src/main/java/com/regnosys/cdm/example/EnumSerialisation.java
  examples/src/main/java/com/regnosys/cdm/example/functions/FixedRateCalculationWithFunction.java
  pom.xml
  rosetta-project/pom.xml
  rosetta-project/src/test/java/com/regnosys/granite/projector/fpml_5_10/Fpml510ProjectionMapperTest.java
  rosetta-project/src/test/java/com/regnosys/granite/projector/fpml_5_10/Fpml510RecordKeepingSampleWriter.java
  rosetta-project/src/test/resources/logback-test.xml
  rosetta-source/src/test/java/org/isda/cdm/documentation/DocumentationCodeValidator.java
  tests/src/test/java/com/regnosys/granite/ingestor/dtcc/DtccIngestion11ServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/dtcc/DtccIngestion9ServiceTest.java
Labels: Category:Technical, Complexity:Small, Target:Development, Criticality:Medium

#2245 [4.x.x] Forward payout extends
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/incomplete-products/fx-derivatives/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/processes/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/products/fx/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-12/products/fx/expectations.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/fx-derivatives/fx-ex26-fxswap-multiple-USIs.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/fx-derivatives/fx-ex29-fx-swap-with-multiple-identifiers.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/processes/msg-partial-termination-xccy.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex01-fx-spot.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex02-spot-cross-w-side-rates.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex03-fx-fwd.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex04-fx-fwd-w-settlement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex05-fx-fwd-w-ssi.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex06-fx-fwd-w-splits.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex07-non-deliverable-forward.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex08-fx-swap.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/fx/fx-ex28-non-deliverable-w-disruption.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex01-fx-spot.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex02-spot-cross-w-side-rates.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex03-fx-fwd.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex04-fx-fwd-w-settlement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex05-fx-fwd-w-ssi.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex06-fx-fwd-w-splits.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex07-non-deliverable-forward.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex08-fx-swap.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/fx/fx-ex28-non-deliverable-w-disruption.json
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity:Small, Criticality:Medium, Target:Production, Category:Modelling

#2251 Fix codefresh bug and update expectations
  RELEASE.md
  codefresh.yml
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/contract-formation/contract-formation-fx-forward-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/execution/execution-fx-forward-func-input.json
Labels: Category:Technical, Criticality:High, Complexity:Small, Target:Production

#2250 Fix codefresh build error, and update expectations
  RELEASE.md
  codefresh.yml
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/contract-formation/contract-formation-fx-forward-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/execution/execution-fx-forward-func-input.json
Labels: Category:Technical, Criticality:High, Complexity:Small, Target:Development

#2248 Patch: DSL 8.2.0
  pom.xml
Labels: Category:Technical, Complexity:Small, Target:Development, Criticality:Medium

#2271 Update README.md
  examples/README.md
Labels: Complexity: Small/Bug/Mapping, Category: Documentation, Criticality: Medium/Low, Target: Production

#2260 TASK-5662: Implement proposed external API guidelines for existing reference data usage (e.g. MIC data) - Add ModuleConfig annotation
  RELEASE.md
  examples/src/main/java/com/regnosys/cdm/example/DemoCdmRuntimeModule.java
  examples/src/main/java/com/regnosys/cdm/example/qualify/QualificationReportExample.java
  pom.xml
  rosetta-project/src/test/java/com/regnosys/granite/projector/AbstractTest.java
  rosetta-project/src/test/java/com/regnosys/granite/projector/fpml_5_10/Fpml510ProjectionMapperTest.java
  rosetta-source/src/main/java/org/finos/cdm/CdmRuntimeModule.java
  rosetta-source/src/test/java/org/isda/cdm/CdmTestsModule.java
  rosetta-source/src/test/java/org/isda/cdm/functions/FunctionInputCreationTest.java
  rosetta-source/src/test/java/org/isda/cdm/functions/SecLendingFunctionInputCreationTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/FisIngestionTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/NativeCdmEventsIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/cme/CMEClearedConfirmTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/cme/CMESubmissionTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/dtcc/DtccIngestion11ServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/dtcc/DtccIngestion9ServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/Fpml510IncompleteProcessesIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/Fpml510IncompleteProductIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/Fpml510ProcessesIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/Fpml510ProductIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/Fpml512ProductIngestionServiceTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/fpml/InvalidProductTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/functions/FunctionTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/ore/OreTradeTest.java
  tests/src/test/java/com/regnosys/granite/ingestor/template/GenerateTemplateExampleJsonWriter.java
Labels: Complexity: Small/Bug/Mapping, Status: needs review, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2265 Create ROADMAP.md
  ROADMAP.md
Labels: Complexity: Small/Bug/Mapping, Category: Documentation, Criticality: Medium/Low, Target: Production

#2286 fix a typo in CDM documentations
  docs/process-model.md
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2285 DSL 8.3.3
  RELEASE.md
  pom.xml
  rosetta-source/src/test/resources/logback-test.xml
  tests/src/test/resources/logback-test.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2287 Remove doc and model references to legacy types: eventType and productType
  documentation/source/event-model.rst
  rosetta-source/src/main/rosetta/event-position-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2273 Marc Gratacos Additions and fixes to Floating Rate Index model
  RELEASE.md
  rosetta-source/src/main/rosetta/observable-asset-fro-enum.rosetta
  rosetta-source/src/main/rosetta/observable-asset-fro-type.rosetta
Labels: Complexity: Minor Change, Rosetta, Target: Development, Criticality: Medium/Low, Category: Modelling

#2291 Update DSL version to 8.3.5
  RELEASE.md
  pom.xml
  rosetta-source/src/main/rosetta/base-staticdata-asset-rates-enum.rosetta
  rosetta-source/src/main/rosetta/observable-asset-enum.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low
