Repository finos/common-domain-model, pull requests merged in 2023-10, with the labels that each got.

#2403 Story-2691: add instruction on how to use the download
  RELEASE.md
  codefresh.yml
  docs/download.md
  docs/eligible-collateral-representation.md
  website/static/img/cdm-graphical-ecs.png
Labels: Complexity: Minor Change, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2441 Hugo Hills Auto-format cdm.product.asset
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2444 Jbaserba commodity delivery 2 with release note
  RELEASE.md
  rosetta-source/src/main/rosetta/observable-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-asset-enum.rosetta
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2466 Update DSL version to 8.9.0 (empty boolean handling)
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low
