Repository finos/common-domain-model, pull requests merged in 2023-12, with the labels that each got.

#2561 Fix CVE scanning
  .github/workflows/cve-scanning.yml
  .gitignore
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: High, Target: Production

#2552 Georgina Tarres TH_Valuation_Instruction
  RELEASE.md
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-common-type.rosetta
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
Labels: Complexity: Minor Change, Rosetta, Criticality: High, Target: Production, Category: Modelling

#2571 Marc Gratacos Updated Qualifying functions for Known Amount ZC
  RELEASE.md
  docs/product-model.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Minor Change, Criticality: High, Target: Production, Category: Modelling

#2574 Apply Marc Gratacos Updated Qualifying functions for Known Amount ZC on 6 dev
  RELEASE.md
  docs/product-model.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2575 Apply Georgina Tarres TH_Valuation_Instruction change on 6 dev
  RELEASE.md
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-common-type.rosetta
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2546 Bataller García Eric Natural Person - Circular reference fix
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2576 Bataller García Eric Deprecated use of personRole in NaturalPerson type
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Criticality: Medium/Low, Target: Production, Category: Modelling

#2585 Lionel Smith-Gordon STORY-2964 Add PartyRole to ECS
  RELEASE.md
  rosetta-source/src/main/rosetta/product-collateral-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Target: Development, Criticality: Medium/Low, Category: Modelling
