Repository finos/common-domain-model, pull requests merged in 2023-09, with the labels that each got.

#2306 Update TaxonomySourceMappingProcessor.java
  RELEASE.md
  rosetta-source/src/main/java/cdm/base/staticdata/asset/common/processor/TaxonomySourceMappingProcessor.java
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2336 index names place holder
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/credit-event/credit-event-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/credit-event/credit-event-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/credit-event/credit-event-obs-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/business-event/credit-event/credit-event-obs-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/dtcc-11-0/DDL_NewTrade3-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex58-execution-advice-trade-initiation-F01-00-func-output.json
  rosetta-source/src/main/resources/result-json-files/dtcc-11-0/DDL_NewTrade3.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-processes/msg-ex59-execution-advice-trade-amendment-F02-00.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-processes/msg-ex60-execution-advice-trade-amendment-correction-F02-10.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cd-ex19-cdx-index-option-pred-clearing.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cdindex-ex01-cdx.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cdindex-ex02-iTraxx.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cdindex-ex03-iTraxx-contractual-supplement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cds-index-tranche.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/cdx-index-option.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/incomplete-products/credit-derivatives/itraxx-index-option.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/processes/msg-ex58-execution-advice-trade-initiation-F01-00.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex01-cdx-seniority-Senior.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex01-cdx-uti.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex02-cdx-seniority-Subordinate.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex02-iTraxx-usi.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex03-cdx-seniority-Other.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdindex-ex03-iTraxx-contractual-supplement-account-versioned.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cds-index-tranche.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/cdx-index-option-uti.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/credit/itraxx-index-option-uti.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/cdindex-ex01-cdx.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/cdindex-ex02-iTraxx.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/cdindex-ex03-iTraxx-contractual-supplement.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/cds-index-tranche.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/cdx-index-option.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/credit/itraxx-index-option.json
  rosetta-source/src/main/resources/result-json-files/native-cdm-events/Example-12-Submission-1.json
  rosetta-source/src/main/resources/result-json-files/native-cdm-events/Example-12-Submission-2.json
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-type.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/observable-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-asset-floatingrate-func.rosetta
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2348 Open source reporting
  RELEASE.md
  examples/pom.xml
  pom.xml
  rosetta-project/pom.xml
  rosetta-source/pom.xml
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex52-execution-advice-trade-partial-novation-C02-00-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/fpml-5-10/processes/msg-ex53-execution-advice-trade-partial-novation-correction-C02-10-func-output.json
  rosetta-source/src/main/rosetta/event-common-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2364 Remove documentation module
  docs/code-snippets/ContractualProduct.snippet
  docs/code-snippets/Product.snippet
  docs/code-snippets/fixed-term-fixed-rate-repo-product.json
  docs/eligible-collateral-representation.md
  docs/event-model.md
  docs/product-model.md
  docs/repurchase-agreement-representation.md
  documentation/.gitignore
  documentation/Dockerfile
  documentation/all.rst
  documentation/build.sh
  documentation/codefresh.yml
  documentation/index.rst
  documentation/latest-template.rst
  documentation/site/_static/favicon.ico
  documentation/site/_static/stylesheets/override.css
  documentation/site/_templates/header.html
  documentation/site/_templates/layout.html
  documentation/site/conf.py
  documentation/site/ingress-prod.yaml
  documentation/site/ingress-rc.yaml
  documentation/source/cdm-guidelines.rst
  documentation/source/cdm-overview.rst
  documentation/source/common-domain-model.rst
  documentation/source/conf.py
  documentation/source/contribution.rst
  documentation/source/download.rst
  documentation/source/eligible-collateral-representation.rst
  documentation/source/event-model.rst
  documentation/source/images/CDM-Development-Process.png
  documentation/source/images/CDM-hoz-logo-print.png
  documentation/source/images/SDLC.png
  documentation/source/images/cdm-components-diagram.png
  documentation/source/images/cdm-distribution.png
  documentation/source/images/cdm-graphical-ecs.png
  documentation/source/images/cdm-namespace.png
  documentation/source/images/cdm-portal.png
  documentation/source/images/cdm-tutorials.png
  documentation/source/images/collateral-asset-identifier-tree.png
  documentation/source/images/composing-primitive-operators.png
  documentation/source/images/event-model-overview.png
  documentation/source/images/finos-cdm-governance-structure.png
  documentation/source/images/namespaces.png
  documentation/source/images/product-namespace.png
  documentation/source/legal-agreements.rst
  documentation/source/links-template.rst
  documentation/source/mapping.rst
  documentation/source/namespace.rst
  documentation/source/process-model.rst
  documentation/source/product-model.rst
  documentation/source/reference-data-model.rst
  documentation/source/repurchase-agreement-representation.rst
  documentation/test-run.sh
  rosetta-source/src/test/java/org/isda/cdm/documentation/DocumentationCodeValidator.java
  rosetta-source/src/test/java/org/isda/cdm/documentation/PatternStreamer.java
  website/sidebars.js
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2370 DSL 8.4.1: bug fix for `extract` on singular input
  RELEASE.md
  pom.xml
  rosetta-source/src/test/java/org/isda/cdm/documentation/DocumentationCodeValidator.java
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: High

#2371 Remove legacy documentation plugins from pom
  README.md
  pom.xml
  rosetta-source/pom.xml
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2375 Include PR link in release notes - Resolves #2374
  docs/contribution.md
Labels: Category: Documentation

#2342 Marc Gratacos Support for ETDs: ListedDerivative & deliveryTerm
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Status: ready for release, Complexity: Minor Change, Rosetta, Criticality: High, Target: Development, Category: Modelling

#2340 ISLA: Modelling Master Agreements
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-enum.rosetta
  rosetta-source/src/main/rosetta/legaldocumentation-master-enum.rosetta
  rosetta-source/src/main/rosetta/legaldocumentation-master-type.rosetta
Labels: Complexity: Minor Change, Rosetta, Target: Development, Criticality: Medium/Low, Category: Modelling

#2384 Remove out-of-date documentation for Java set up
  RELEASE.md
  docs/cdm-guidelines.md
  rosetta-source/src/test/java/org/isda/cdm/documentation/DocumentationCodeValidator.java
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2369 Bataller García Eric Adding CompressionServiceProvider - Party role
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-enum.rosetta
Labels: Complexity: Minor Change, Rosetta, Criticality: High, Target: Development, Category: Modelling

#2386 STORY-2607: CDM Types, Attributes and Enums in an excel/csv format
  RELEASE.md
  codefresh.yml
  docs/download.md
  pom.xml
  rosetta-source/pom.xml
Labels: Complexity: Minor Change, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2394 Updated DSL to 8.6.2
  RELEASE.md
  pom.xml
  rosetta-project/src/main/java/com/regnosys/granite/projector/fpml_5_10/Fpml510ProjectionMapper.java
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2380 Jan Baserba Commodity Delivery (second resubmission)
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-identifier-enum.rosetta
  rosetta-source/src/main/rosetta/base-staticdata-identifier-type.rosetta
  rosetta-source/src/main/rosetta/product-asset-enum.rosetta
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity: Minor Change, Rosetta, Criticality: High, Target: Development, Category: Modelling

#2391 Windows build added to github workflows
  .github/workflows/windows-build.yml
Labels: Complexity: Minor Change, Category: Technical/Patch, Criticality: High, Target: Development

#2376 Georgina Tarres Terminating Event Mappings
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-workflowstep-synonym.rosetta
Labels: Complexity: Minor Change, Rosetta, Target: Development, Criticality: Medium/Low, Category: Modelling

#2397 Story-2657: Relocate test pack samples to incomplete-products folders
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-12/incomplete-products/equity/eqs-ex04-zero-strike-long-form.xml
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-12/incomplete-products/equity/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-12/products/equity/expectations.json
  rosetta-source/src/main/resources/ingestions/ingestions.json
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-processes-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-products-rates-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-12-incomplete-products-equity-aggregated-mapping-failure-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-12-incomplete-products-equity-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-12-products-equity-aggregated-mapping-failure-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-12-products-equity-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-12-products-repo-failed-mappings-report.csv
  rosetta-source/src/main/resources/mapping-analytics/native-cdm-events-failed-mappings-report.csv
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/incomplete-products/equity/eqs-ex04-zero-strike-long-form.json
  tests/src/test/java/com/regnosys/ingest/fpml/Fpml512IncompleteProductIngestionServiceTest.java
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2410 Update DSL version to 8.8.0 and bundle version to 7.9.0 (Func call rules, and extract empty bug)
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2392 [5.0.0-dev.x] Add qualification for bond and equity forwards
  RELEASE.md
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
  rosetta-source/src/main/rosetta/product-template-func.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling
