Repository finos/common-domain-model, pull requests merged in 2023-11, with the labels that each got.

#2439 Minesh Patel Added CheckEligibilityByDetails function
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-4y-eu-security-debt-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-4y-eu-security-debt-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-4y-eu-security-debt.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-eurex-vanilla-security-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-eurex-vanilla-security-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-eurex-vanilla-security.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/execution-descriptor.json
  rosetta-source/src/main/rosetta/product-collateral-func.rosetta
Labels: Complexity: Minor Change, Rosetta, Target: Development, Criticality: Medium/Low

#2477 Vernon Alden-Smith ISO Country Codes connect to asset issuer criteria
  RELEASE.md
  docs/eligible-collateral-representation.md
  docs/legal-agreements.md
  examples/src/test/java/com/regnosys/cdm/example/functions/CreateEligibleCollateralSpecificationFromInstructionTest.java
  examples/src/test/resources/merge-eligible-collateral-expected.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-4y-eu-security-debt-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-4y-eu-security-debt-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-eurex-vanilla-security-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/check-eligibility-eurex-vanilla-security-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/merge-criteria-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/eligible-collateral/merge-criteria-func-output.json
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
  rosetta-source/src/main/rosetta/product-collateral-func.rosetta
  rosetta-source/src/main/rosetta/product-collateral-type.rosetta
  rosetta-source/src/test/java/org/isda/cdm/functions/FunctionInputCreationTest.java
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2456 BUG-557 sec-lending qualification with updated Expectations
  RELEASE.md
  rosetta-source/src/main/java/cdm/event/workflow/processor/FISMapperMappingProcessor.java
  rosetta-source/src/main/java/cdm/security/lending/functions/SettlementFunctionHelper.java
  rosetta-source/src/main/resources/cdm-sample-files/fis/expectations.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/cancellation-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/clearing-via-novation-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/clearing-via-open-offer-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/on-demand-interest-payment-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/on-demand-rate-change-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/pair-off-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-execution-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/roll-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/shaping-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/allocation/allocation-sec-lending-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/allocation/allocation-sec-lending-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/block-execution-instruction.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/create-security-lending-invoice-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/create-security-lending-invoice-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/full-return-settlement-workflow-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/full-return-settlement-workflow-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/new-settlement-workflow-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/new-settlement-workflow-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/part-return-settlement-workflow-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/part-return-settlement-workflow-func-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/reallocation/reallocation-pre-settled-func-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/sec-lending/reallocation/reallocation-pre-settled-func-output.json
  rosetta-source/src/main/resources/result-json-files/fis/isla1.json
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
  rosetta-source/src/main/rosetta/observable-event-func.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Criticality: High, Target: Development, Category: Modelling

#2519 Jan Baserba Forward and Option Commodity Delivery
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#2520 Update RELEASE.md
  RELEASE.md
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2521 Adding UPI mapping for ProductIdTypeEnum from scheme
  RELEASE.md
  rosetta-source/src/main/java/cdm/base/staticdata/asset/common/processor/ProductIdentifierSourceMappingProcessor.java
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2529 Repo lifecycle additions (Partial Delivery, Reprice, Adjustment, Substitution) Replaces 2472
  RELEASE.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond-execution-descriptor.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/partial-delivery-delivered-price-quantity.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/partial-delivery-effective-date.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/partial-delivery-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/partial-delivery-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/partial-delivery.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-adjustment-effective-date.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-adjustment-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-adjustment-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-adjustment.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-reprice-effective-date.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-reprice-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-reprice-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-reprice.md
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution-collateral.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution-effective-date.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution-input.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution-output.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution-price-quantity.json
  rosetta-source/src/main/resources/cdm-sample-files/functions/repo-and-bond/repo-substitution.md
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/test/java/org/isda/cdm/functions/FunctionInputCreationTest.java
Labels: Complexity: Small/Bug/Mapping, Criticality: High, Target: Production, Category: Modelling

#2528 update bundle and cdm version
  RELEASE.md
  pom.xml
  rosetta-source/src/main/rosetta/base-datetime-enum.rosetta
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
  rosetta-source/src/main/rosetta/base-staticdata-asset-rates-enum.rosetta
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-position-type.rosetta
  rosetta-source/src/main/rosetta/observable-asset-enum.rosetta
  rosetta-source/src/test/java/org/isda/cdm/functions/ModelClassValidationTest.java
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2539 Rguitart position business event after multiple cardinality
  RELEASE.md
  rosetta-source/src/main/rosetta/event-common-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Target: Production, Category: Modelling

#2544 Rvincent qualify contract formation enhancement for transfer
  RELEASE.md
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Criticality: Medium/Low, Target: Production, Category: Modelling

#2533 DSL update: type coercions
  RELEASE.md
  pom.xml
  rosetta-source/src/main/rosetta/observable-common-func.rosetta
Labels: Complexity: Minor Change, Category: Technical/Patch, Criticality: High, Target: Production
