Repository finos/common-domain-model, pull requests merged in 2023-06, with the labels that each got.

#2171 Update DSL version to 7.7.3 and bundle version 6.5.3 (type format validation support)
  RELEASE.md
  pom.xml
  rosetta-source/pom.xml
  rosetta-source/src/test/java/org/isda/cdm/functions/ModelClassValidationTest.java
  scheme-import/src/test/java/com/regnosys/granite/schemaimport/SchemeImporterTest.java
Labels: Patch/Documentation

#2170 Move logging implementations to test scope
  pom.xml
  rosetta-source/src/main/rosetta/namespace-hierarchy.json
  scheme-import/pom.xml
  tests/src/test/java/com/regnosys/granite/ingestor/schemaimport/SchemeImporterTest.java
Labels: Patch/Documentation

#2178 update release note
  RELEASE.md
Labels: Patch/Documentation

#2184 DSL 7.9.3: mandatory `then` and reduction of square brackets
  RELEASE.md
  documentation/source/event-model.rst
  documentation/source/process-model.rst
  pom.xml
  rosetta-source/src/main/rosetta/base-datetime-func.rosetta
  rosetta-source/src/main/rosetta/base-math-func.rosetta
  rosetta-source/src/main/rosetta/base-staticdata-party-func.rosetta
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
  rosetta-source/src/main/rosetta/observable-asset-calculatedrate-func.rosetta
  rosetta-source/src/main/rosetta/observable-asset-fro-func.rosetta
  rosetta-source/src/main/rosetta/observable-asset-func.rosetta
  rosetta-source/src/main/rosetta/observable-common-func.rosetta
  rosetta-source/src/main/rosetta/product-asset-calculation-func.rosetta
  rosetta-source/src/main/rosetta/product-asset-floatingrate-func.rosetta
  rosetta-source/src/main/rosetta/product-asset-func.rosetta
  rosetta-source/src/main/rosetta/product-collateral-func.rosetta
  rosetta-source/src/main/rosetta/product-template-func.rosetta
Labels: Minor Enhancement/Change

#2196 Revert "nexus release"
  codefresh.yml
  rosetta-source/pom.xml
  rosetta-source/src/main/resources/build-resources/create-deploy-pom.sh
  rosetta-source/src/main/resources/kotlin-build-resources/kotlin-build-pom.xml
  rosetta-source/src/main/resources/scala-build-resources/build.sbt
  rosetta-source/src/main/resources/scala-build-resources/project/Dependencies.scala
  rosetta-source/src/main/resources/scala-build-resources/project/build.properties
  rosetta-source/src/main/resources/scala-build-resources/project/plugins.sbt
Labels: Patch/Documentation

#2177 Brain Lynn Collateral interest calculation june 2023 updated expectations
  RELEASE.md
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/rates/ird-ex27-inverse-floater.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/rates/ird-ex35-inverse-floater-inverse-vs-floating.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/rates/ird-ex27-inverse-floater.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/rates/ird-ex40-rfr-avg-swap-obs-period-shift.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/rates/ird-ex46-rfr-compound-swap-lookback-oet-mmviq.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-12/products/rates/ird-ex47-rfr-compound-swap-lookback-oet-rvfq.json
  rosetta-source/src/main/rosetta/base-datetime-enum.rosetta
  rosetta-source/src/main/rosetta/base-datetime-type.rosetta
  rosetta-source/src/main/rosetta/legaldocumentation-common-enum.rosetta
  rosetta-source/src/main/rosetta/legaldocumentation-common-type.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-collateral-enum.rosetta
  rosetta-source/src/main/rosetta/product-collateral-type.rosetta
Labels: Minor Enhancement/Change

#2202 Update DSL version to 7.10.0 (Guice conditions) and bundle version 6.7.0
  RELEASE.md
  isda-demo/src/main/java/com/regnosys/cdm/example/Validation.java
  pom.xml
Labels: Patch/Documentation

#2204 4.0 Release notes
  RELEASE.md
Labels: Criticality:High, Complexity:Small, Category:Documentation, Target:Production

#2208 CDM 5-dev release notes
  RELEASE.md
Labels: Criticality:High, Complexity:Small, Target:Development, Category:Documentation

#2238 Updated process to generate deployment POM
  codefresh.yml
  rosetta-source/src/main/resources/build-resources/create-deploy-pom.py
  rosetta-source/src/main/resources/build-resources/python/python-developer.txt
Labels: Category:Technical, Complexity:Small, Complexity:Medium
