Repository finos/common-domain-model, pull requests merged in 2024-08, with the labels that each got.

#3084 CDM documentation corrections
  docs/cdm-overview.md
Labels: Category: Documentation

#3108 story 959 task-5050: config update 5.x.x
  RELEASE.md
  pom.xml
  rosetta-source/src/main/resources/rosetta-config.yml
Labels: Complexity: Minor Change, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#3107 story 959 task-5050: config update
  RELEASE.md
  pom.xml
  rosetta-source/src/main/resources/rosetta-config.yml
Labels: Complexity: Minor Change, Category: Technical/Patch, Target: Development, Criticality: Medium/Low
