Repository finos/common-domain-model, pull requests merged in 2024-07, with the labels that each got.

#3018 Update ISOCurrencyCodeEnum based on updated scheme ISO Standard 4217
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-common-settlement-type.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Rosetta

#3031 PROD Bug Fix - Modification to product condition for Floating Rate Option
  RELEASE.md
  rosetta-source/src/main/rosetta/observable-asset-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Complexity: Minor Change, Rosetta, Target: Production

#3032 PROD Bug Fix - Modification to product condition for FpML_cd_30
  RELEASE.md
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Target: Production

#3035 Dev Bug Fix - Modification to product condition for FpML_cd_30 and Floating Rate Option
  RELEASE.md
  rosetta-source/src/main/rosetta/observable-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Complexity: Minor Change, Target: Development, Criticality: Medium/Low, Category: Modelling

#3042 story 928 task-4879: add https notice to docs
  docs/cdm-guidelines.md
  docs/download.md
  website/versioned_docs/version-5.13.0/cdm-guidelines.md
  website/versioned_docs/version-5.13.0/download.md
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#3053 Updates to Roadmap.md by Brian Lynn
  ROADMAP.md
Labels: Category: Documentation

#3052 Updates to Governance.md by Brian Lynn
  GOVERNANCE.md
Labels: Category: Documentation
