Repository finos/common-domain-model, pull requests merged in 2024-02, with the labels that each got.

#2675 Payal Khanna format
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/observable-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-common-enum.rosetta
Labels: Complexity: Small/Bug/Mapping, Rosetta, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2690 [6.0.0-dev.x] JSON schema support
  RELEASE.md
  codefresh.yml
  docs/download.md
  pom.xml
  rosetta-source/pom.xml
Labels: Complexity: Minor Change, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2686 [5.x.x] JSON schema support
  RELEASE.md
  codefresh.yml
  docs/download.md
  pom.xml
  rosetta-source/pom.xml
Labels: Complexity: Minor Change, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#2693 [6.0.0-dev.x] STORY-3109: A DRR user can get valid output from ToDateTime function
  RELEASE.md
  rosetta-source/src/main/java/cdm/base/datetime/functions/ToTimeImpl.java
  rosetta-source/src/main/java/org/finos/cdm/CdmRuntimeModule.java
  rosetta-source/src/main/rosetta/base-datetime-func.rosetta
  rosetta-source/src/test/java/cdm/base/datetime/functions/ToDateTimeTest.java
  rosetta-source/src/test/java/cdm/base/datetime/functions/ToTimeImplTest.java
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2689 Readme.md and website changes
  .github/Approval-Process.png
  .github/Group-Roles-Scope.png
  .github/bulb.svg
  .github/finos-cdm-governance-structure.png
  .github/use-of-github.png
  README.md
  website/docusaurus.config.js
  website/static/pdfs/Why_CDM_ .pdf
Labels: Complexity: Minor Change, Category: Documentation, Criticality: Medium/Low

#2719 Mcarrera commodity forwards update expectations PROD
  RELEASE.md
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Target: Production

#2727 Mcarrera cdm day count fractions release development
  RELEASE.md
  rosetta-source/src/main/rosetta/base-datetime-daycount-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Target: Development

#2735 Rguitart commodity classification release dev
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Modelling

#2734 Rguitart commodity classification release prod
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Production, Category: Modelling

#2724 Ebataller isdaiifm tma master agreement type enum release development
  RELEASE.md
  rosetta-source/src/main/rosetta/legaldocumentation-master-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Minor Change, Target: Development, Category: Modelling

#2720 Ebataller isdaiifm tma master agreement type enum release prod
  RELEASE.md
  rosetta-source/src/main/rosetta/legaldocumentation-master-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Minor Change, Target: Production, Category: Modelling

#2733 Gopazo qualifying functions etd release prod
  RELEASE.md
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Minor Change, Target: Production, Category: Modelling

#2732 Gopazo qualifying functions etd release dev
  RELEASE.md
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Minor Change, Target: Development, Category: Modelling
