Repository finos/common-domain-model, pull requests merged in 2024-01, with the labels that each got.

#2605 [5.x.x] STORY-3031: Update ISO country enum to keep in sync with latest ISO 4217
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#2604 [6.0.0-dev.x] STORY-3031: Update ISO country enum to keep in sync with latest ISO 4217
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2607 [6.0.0-dev.x] Update CDM to use DSL version 9.3.0
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2602 [6.0.0-dev.x] BUG-560: Bond forwards do not qualify
  RELEASE.md
  rosetta-source/src/main/java/cdm/product/template/processor/InterestRateForwardDebtPriceMappingProcessor.java
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/products/rates/bond-fwd-generic-ex01.xml
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/products/rates/bond-fwd-generic-ex02.xml
  rosetta-source/src/main/resources/cdm-sample-files/fpml-5-10/products/rates/expectations.json
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-products-rates-aggregated-mapping-failure-report.csv
  rosetta-source/src/main/resources/mapping-analytics/fpml-5-10-products-rates-failed-mappings-report.csv
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/rates/bond-fwd-generic-ex01.json
  rosetta-source/src/main/resources/result-json-files/fpml-5-10/products/rates/bond-fwd-generic-ex02.json
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
  tests/src/test/resources/logback-test.xml
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2609 update-bundle-version
  RELEASE.md
  pom.xml
  rosetta-source/src/main/resources/ingestions/ingestions.json
  rosetta-source/src/main/resources/ingestions/isla-ingestions.json
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2617 Payal Khanna format
  rosetta-source/src/main/rosetta/base-staticdata-asset-common-enum.rosetta
  rosetta-source/src/main/rosetta/base-staticdata-asset-desc.rosetta
  rosetta-source/src/main/rosetta/event-common-enum.rosetta
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-common-type.rosetta
  rosetta-source/src/main/rosetta/event-position-func.rosetta
  rosetta-source/src/main/rosetta/event-position-type.rosetta
  rosetta-source/src/main/rosetta/event-qualification-func.rosetta
  rosetta-source/src/main/rosetta/event-workflow-type.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/observable-asset-calculatedrate-enum.rosetta
  rosetta-source/src/main/rosetta/observable-asset-calculatedrate-type.rosetta
  rosetta-source/src/main/rosetta/observable-asset-fro-func.rosetta
  rosetta-source/src/main/rosetta/observable-asset-func.rosetta
  rosetta-source/src/main/rosetta/observable-common-enum.rosetta
  rosetta-source/src/main/rosetta/observable-event-func.rosetta
  rosetta-source/src/main/rosetta/product-collateral-enum.rosetta
  rosetta-source/src/main/rosetta/product-collateral-func.rosetta
  rosetta-source/src/main/rosetta/product-collateral-type.rosetta
  rosetta-source/src/main/rosetta/product-common-schedule-type.rosetta
  rosetta-source/src/main/rosetta/product-common-settlement-func.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
  rosetta-source/src/main/rosetta/product-template-type.rosetta
Labels: Rosetta

#2627 [master] Update DSL version to 9.3.1
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2626 [5.x.x] Update DSL version to 9.3.1
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#2633 Jan Baserba FRO Mappings Update
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2635 Jan Baserba FRO_Mappings_Update_prod
  RELEASE.md
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Criticality: Medium/Low, Target: Production, Category: Modelling

#2620 STORY-3030 Updates to ECS Collateral documentation (docs only)
  docs/eligible-collateral-representation.md
  website/static/img/cdm-graphical-ecs.png
Labels: Complexity: Small/Bug/Mapping, Target: Development, Category: Documentation, Criticality: Medium/Low

#2640 Website changes and readme.md changes
  .github/cdm-roadmap-2024-1.png
  .github/cdm-roadmap-2024-2.png
  README.md
  ROADMAP.md
  docs/cdm-overview.md
  docs/get-involved.md
  website/static/img/cdm-roadmap-2024-1.png
  website/static/img/cdm-roadmap-2024-2.png
Labels: Status: needs review, Category: Documentation, Criticality: Medium/Low

#2646 [6xx] DSL update
  RELEASE.md
  pom.xml
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Target: Development, Criticality: Medium/Low

#2648 Marc Gratacos Minor updates to the Zero Coupon Qualification - Release
  RELEASE.md
  docs/product-model.md
  rosetta-source/src/main/rosetta/product-asset-type.rosetta
  rosetta-source/src/main/rosetta/product-qualification-func.rosetta
Labels: Complexity: Small/Bug/Mapping, Target: Development, Criticality: Medium/Low, Category: Modelling

#2649 Nicholas Moger Create_Execution Update - Release PR
  RELEASE.md
  rosetta-source/src/main/rosetta/event-common-func.rosetta
  rosetta-source/src/main/rosetta/event-common-type.rosetta
Labels: Complexity: Minor Change, Criticality: Medium/Low, Target: Production, Category: Modelling

#2656 [5.x.x] Fix bond forward mapping issues
  RELEASE.md
  pom.xml
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#2657 [master] Bond fwd mapping issues
  RELEASE.md
  pom.xml
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Small/Bug/Mapping, Category: Technical/Patch, Criticality: Medium/Low, Target: Production

#2653 Manuel Carrera PTRR Service Provider dev
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Minor Change, Rosetta, Target: Development, Criticality: Medium/Low, Category: Modelling

#2651 Manuel Carrera PTRR Service Provider - Release PR
  RELEASE.md
  rosetta-source/src/main/rosetta/base-staticdata-party-enum.rosetta
  rosetta-source/src/main/rosetta/mapping-fpml-confirmation-tradestate-synonym.rosetta
Labels: Complexity: Minor Change, Criticality: Medium/Low, Target: Production, Category: Modelling
